### PR TITLE
Add preserveKeys argument

### LINKED ISSUE #23: Missing keys from Tailwind config
@dobromir-hristov  Following up #8 

#15 introduced a feature where disabled plugins are removed from the export. 

Some Tailwind config keys are global and not related to plugins and thus removed (`colors`, `screens`, `spacing`, maybe more or custom ones).

> How should that whitelist be defined or passed?

With some config key like `keepKeys` or `preserveKeys`? 

```js
const converter = new TailwindExportConfig({
  config: 'path/to/tailwind.config.js',
  destination: 'converted/file/destination',
  format: 'scss',
  prefix: 'tw',
  flat: true,
  quotedKeys: true,
  preserveKeys: ['colors', 'screens']
})
```

I think wanted stuff like `colors` and `screens` might be preserved by default. 

Let me know what you think.

### PR DESCRIPTION
**Pull request by nlemoine**
Fixes #23

### CODE REVIEW

**Review by dobromir-hristov — APPROVED** [review]
Awesome work. Will test it tonight, but it looks solid :)

**Comment by dobromir-hristov** [comment]
Tested it out, its great. Want to finish it and add docs to the Readme?

**Comment by nlemoine** [comment]
Done!

**Comment by nlemoine** [comment]
Thanks! Can you publish a new tag?

**Comment by dobromir-hristov** [comment]
I can't right now, at work.

**Pull request merged**
