### PR TITLE
Test added: [less] array to comma seperated string

### PR DESCRIPTION
**Pull request by jordypereira**
Hey, I'm quite new to OSS, and I want to contribute.
That's why I'm starting with contributing a little test that checks if it correctly translates an array to a string.

Any feedback is appreciated.

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
The test is not bad, you are reusing the testing setup, which is awesome, however is it clear what you are trying to do?
I as a fellow dev, had to start looking through the code to figure out what the outcome should be. Because this is such a simple example, it is wise to pass it a string and assert a string, plain and simple.

The above test uses a snapshot test with a large collection of data, which also has cons. You have the snapshot, which will show you what fails, but only if it is in a subset of the entire snapshot. If two large parts of it change/move around, that snapshot becomes useless.

**Comment by jordypereira** [comment]
If I understand correctly, 
I have made it too reusable for the current use cases, sacrificing readability.
Also, the test is not useful, because the snapshot will detect if there is an oddity.

I also saw that you were basically duplicating the tests for each framework, and wondered if there was a way to make a test-constructor where you could just pass in the right converter and name.

Anyhow, thanks for your feedback!

**Comment by dobromir-hristov** [comment]
Well the snapshot does catch it, but it was made because I was lazy and in a hurry, yet still gets the job done.

The test is duplicated now, but as more and more methods are added, and new logic is introduced, the tests will start to look different.

Too much automation is not always good. Its OK to have a basic script to prepare your tests, but when you test itself becomes a giant logic mess, its bad.

**Comment by jordypereira** [comment]
I simplified the test. If it's not needed we can close this PR

**Comment by dobromir-hristov** [comment]
Well the way you did it now, checks fonts, but what about backgrounds? What about border radiuses? How is fonts special? Get what I am saying?
A test case must prove a point, should test .. well a case. Why do we write the test? To make sure a specific feature works. Transforming font-family is not a specific feature, transforming an array of values to a map is however.

But as I said, in this case, the snapshot tests work perfectly, as we know exactly what the outcome will be and cover the entire format of the tailwind config.

**Comment by jordypereira** [comment]
Fonts are special because they are the only object with arrays nested inside of them. 
I was testing if it also converts an array correctly instead of a single key value.

Given:

```js
  sans: ['Inter', 'Helvetica', 'Arial', 'sans-serif'],
```

Into 

```less
@font-sans: Inter, Helvetica, Arial, sans-serif;
```

**Comment by dobromir-hristov** [comment]
Aha OK you got a point. Well, then its OK. Do we have the same edge case for other types? If we do, we need to test there too. Otherwise we can move this to the more general test cases.

**Comment by jordypereira** [comment]
They should all behave the same. 
I can generalize my code again as I had it first, consisting of variables.
And then call the test, passing it the language prefix and suffix. 

Not sure what the best way to do this is.

**Pull request closed without merging**
